export const GAME_SESSION_STATE = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  DELETED: 'DELETED',
};

export const BUTTON_INTERACTIONS = {
  BUTTON_PRESS: 'BUTTON_PRESS',
  BUTTON_RELEASE: 'BUTTON_RELEASE',
};

export const PUBNUB_HISTORY_LIMIT = 25;
